spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hong_oms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password:
  application:
    name: order-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:18080
      datasource:
        nacos:
          nacos:
            serverAddr: 127.0.0.1:8848
            groupId: DEFAULT_GROUP
            dataId: sentinelFlowRule
            data-type: json
            ruleType: flow
    openfeign:
      client:
        config:
          default:
            connect-timeout: 2000
            read-timeout: 2000
server:
  port: 9002